---
title: 'HW #5'
author: "Molly Murphy"
date: "2025-12-01"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, libraries}
library(tidyverse)
library(tigris)
library(sf)
library(ggthemes)
```

```{r, reading in homicide csv}
homicides <- read_csv("../data/homicide-data.csv")
```

```{r, filtering to Oakland, CA}
oak_homicides <- homicides %>% 
  filter(city == "Oakland") %>% 
  st_as_sf(coords = c("lon", "lat")) %>% 
  st_set_crs(4269) %>% 
  mutate(victim_race = factor(victim_race),
         victim_race = fct_lump_n(victim_race, n = 3))
```


```{r, oakland sf}
oakland <- places(state = "CA", 
                           cb = TRUE, 
                           class = "sf") %>% 
  filter(NAME == "Oakland")

alameda_bg <- block_groups(state = "CA", 
                           county = "Alameda", 
                           cb = TRUE, 
                           class = "sf")

oakland_bg <- st_filter(alameda_bg, oakland)
```

```{r, plot}
ggplot() +
  geom_sf(data = oakland_bg, aes(), fill = "white") +
  geom_sf(data = oak_homicides, aes(color = victim_race), size = 0.6) +
  facet_wrap(. ~ disposition, ncol = 2) +
  theme_few() +
  labs(color = "Race of Victim", y = "Latitude", x = "Longitude") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) +
  ggtitle("Homicides in Oakland, CA by status") 
```

